export const user_actions = {
  SIGNUP_ACTION: 'SIGNUP_ACTION',
  SIGNIN_ACTION: 'SIGNIN_ACTION',
  SIGNOUT_ACTION: 'SIGNOUT_ACTION',
  FETCHED_PEOPLE: 'FETCHED_PEOPLE',
  FETCHED_FRIENDS: 'FETCHED_FRIENDS',
  SEND_CONNECTION_REQUEST: 'SEND_CONNECTION_REQUEST',
  FETCHED_FRIEND_REQUESTS: 'FETCHED_FRIEND_REQUESTS',
  UNFRIEND_USER: 'UNFRIEND_USER',
  UNDO_UNFRIENDES_USER: 'UNDO_UNFRIENDES_USER',
  GET_LAST_MESSAGES: 'GET_LAST_MESSAGES',
};

export const chat_actions = {
  USER_ITEM_SELECTED: 'USER_ITEM_SELECTED',
  FETCHED_MESSAGES_STARTED: 'FETCHED_MESSAGES_STARTED',
  FETCHED_MESSAGES: 'FETCHED_MESSAGES',
  INITIAL_CONNECTION_ESTABLISHED: 'INITIAL_CONNECTION_ESTABLISHED',
  UPDATE_UNREAD_MESSAGES: 'UPDATE_UNREAD_MESSAGES',
  READ_USER_UNREAD_MESSAGES: 'READ_USER_UNREAD_MESSAGES',
  CURRENT_USERS_ONLINE: 'CURRENT_USERS_ONLINE',
  REMOVE_CURRENT_USER_ONLINE: 'REMOVE_CURRENT_USER_ONLINE',
};
