export const auth_actions = {
  SIGNUP_ACTION: 'SIGNUP_ACTION',
  SIGNIN_ACTION: 'SIGNIN_ACTION',
  SIGNOUT_ACTION: 'SIGNOUT_ACTION',
};
export const reaction_actions = {
  TYPING_STARTED: 'TYPING_STARTED',
  TYPING_STOPPED: 'TYPING_STOPPED',
};

export const user_actions = {
  SIGNUP_ACTION: 'SIGNUP_ACTION',
  SIGNIN_ACTION: 'SIGNIN_ACTION',
  SIGNOUT_ACTION: 'SIGNOUT_ACTION',
  FETCHED_PEOPLE: 'FETCHED_PEOPLE',
  FETCHED_FRIENDS: 'FETCHED_FRIENDS',
  SEND_CONNECTION_REQUEST: 'SEND_CONNECTION_REQUEST',
  FETCHED_FRIEND_REQUESTS: 'FETCHED_FRIEND_REQUESTS',
  UNFRIEND_USER: 'UNFRIEND_USER',
  UNDO_UNFRIENDES_USER: 'UNDO_UNFRIENDES_USER',
  CONFIRM_UNFRIENDING_ACTION: 'CONFIRM_UNFRIENDING_ACTION',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  FETCHED_BLOCKED_FRIENDS: 'FETCHED_BLOCKED_FRIENDS',
  UNBLOCKED_FRIEND: 'UNBLOCKED_FRIEND',
  BLOCKED_FRIEND: 'BLOCKED_FRIEND',
  FETCHED_SENT_FRIEND_REQUESTS: 'FETCHED_SENT_FRIEND_REQUESTS',
  REMOVE_SENT_FRIEND_REQUEST: 'REMOVE_SENT_FRIEND_REQUEST',
  FETCHED_UNACCEPTED_FRIEND_REQUESTS: 'FETCHED_UNACCEPTED_FRIEND_REQUESTS',
  DECLINE_FRIEND_REQUEST: 'DECLINE_FRIEND_REQUEST',
  ACCEPT_FRIEND_REQUEST: 'ACCEPT_FRIEND_REQUEST',
};

export const chat_actions = {
  USER_ITEM_SELECTED: 'USER_ITEM_SELECTED',
  GET_LAST_MESSAGES: 'GET_LAST_MESSAGES',
  FETCHED_MESSAGES_STARTED: 'FETCHED_MESSAGES_STARTED',
  FETCHED_MESSAGES: 'FETCHED_MESSAGES',
  INITIAL_CONNECTION_ESTABLISHED: 'INITIAL_CONNECTION_ESTABLISHED',
  UPDATE_UNREAD_MESSAGES: 'UPDATE_UNREAD_MESSAGES',
  READ_USER_UNREAD_MESSAGES: 'READ_USER_UNREAD_MESSAGES',
  CURRENT_USERS_ONLINE: 'CURRENT_USERS_ONLINE',
  REMOVE_CURRENT_USER_ONLINE: 'REMOVE_CURRENT_USER_ONLINE',
  SEND_PERSONAL_MESSAGE_SUCCESS: 'SEND_PERSONAL_MESSAGE_SUCCESS',
  SEND_PERSONAL_MESSAGE_FAILURE: 'SEND_PERSONAL_MESSAGE_FAILURE',
};

export const api_loader_action = {
  USER_INFO_UPDATE_STARTED: 'USER_INFO_UPDATE_STARTED',
  USER_INFO_UPDATE_ENDED: 'USER_INFO_UPDATE_ENDED',
  USER_PROFILE_PHOTO_UPDATE_STARTED: 'USER_PROFILE_PHOTO_UPDATE_STARTED',
  USER_PROFILE_PHOTO_UPDATE_ENDED: 'USER_PROFILE_PHOTO_UPDATE_ENDED',
  USER_PROFILE_PHOTO_UPDATE_ERROR: 'USER_PROFILE_PHOTO_UPDATE_ERROR',
};
